apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/KiranBK18/newrepo.git'
    targetRevision: HEAD
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true